# Generated by Django 5.1.6 on 2025-02-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_remove_profile_bio_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialorder',
            options={'verbose_name_plural': 'orders'},
        ),
    ]
