# Generated by Django 5.1.6 on 2025-02-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_materialorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='code',
            field=models.CharField(default='Enter code', max_length=200),
        ),
    ]
