# Generated by Django 5.1.6 on 2025-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_alter_materialorder_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='request_type',
            field=models.CharField(choices=[('release', 'Release Request'), ('Receipt', 'Receipt Request')], default='Release', max_length=20),
        ),
    ]
