# Generated by Django 5.1.6 on 2025-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_materialorder_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='processed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='remaining_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='request_type',
            field=models.CharField(choices=[('Release', 'Release Request'), ('Receipt', 'Receipt Request')], default='Release', max_length=20),
        ),
    ]
