# Generated by Django 5.1.6 on 2025-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_materialorder_processed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
